source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

target 'CHFoundation' do
	pod 'PromiseKit', '4.1.0'
end

target 'CHFoundationTests' do
	pod 'PromiseKit', '4.1.0'
end
